---
cidr_networks:
  container: 172.16.11.0/24
  tunnel: 172.16.12.0/24
  storage: 172.16.13.0/24

#used_ips:
#  - "172.16.1.1,172.16.1.120"
#  - "172.16.1.250,172.16.1.254"

global_overrides:
  internal_lb_vip_address: 172.16.11.1
  external_lb_vip_address: 172.16.11.1
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  infra1:
    ip: 172.16.11.1

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  infra1:
    ip: 172.16.11.1

# load balancer
haproxy_hosts:
  infra1:
    ip: 172.16.11.1

###
### OpenStack
###

# keystone
identity_hosts:
  infra1:
    ip: 172.16.11.1

# cinder api services
storage-infra_hosts:
  infra1:
    ip: 172.16.11.1

# glance
image_hosts:
  infra1:
    ip: 172.16.11.1

# nova api, conductor, etc services
compute-infra_hosts:
  infra1:
    ip: 172.16.11.1

# heat
orchestration_hosts:
  infra1:
    ip: 172.16.11.1

# horizon
dashboard_hosts:
  infra1:
    ip: 172.16.11.1

# neutron server, agents (L3, etc)
network_hosts:
  infra1:
    ip: 172.16.11.1

# nova hypervisors
compute_hosts:
  compute1:
    ip: 172.16.11.2

# cinder storage host (LVM-backed)
storage_hosts:
  compute1:
    ip: 172.16.11.2
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "172.16.13.1"
